  - yum:
      name: "{{ extra_packages }}"

  - copy:
      src: /home/leme/ansible/part2_lab2.1/my.cnf
      dest: "{{ configure_database_path }}"
      owner: mysql
      group: mysql
      mode: 0644
      seuser: system_u
      setype: mysqld_etc_t
      force: yes

  - service:
      name: "{{ db_service }}"
      state: started
      enabled: true
